# 性能优化配置文件 - 针对48GB GPU优化
# 内存优化参数
memory_optimization:
  dynamic_batch_size: false  # 48GB显存足够大，不需要动态调整
  max_memory_usage: 0.95    # 提高到95%，充分利用48GB显存
  gradient_accumulation_steps: 2  # 不需要梯度累积，直接使用大批量
  mixed_precision: true     # 保持混合精度以节省内存
  memory_efficient_attention: false  # 48GB显存足够，不需要内存高效注意力
  gradient_checkpointing: false  # 显存充足，不需要梯度检查点
  pin_memory: true
  num_workers: 16          # 增加worker数量，充分利用CPU
  prefetch_factor: 4       # 增加预取因子
  persistent_workers: true

# 训练优化参数 - 针对48GB GPU
training_optimization:
  batch_size: 16           # 大幅增加批处理大小
  update_freq: 2           # 减少更新频率，增加有效批大小
  clip_norm: 0.25
  lr: 3.2e-4              # 稍微提高学习率
  xvlm_lr: 6e-5           # 提高XVLM学习率

# 模型优化参数 - 充分利用48GB显存
model_optimization:
  AOA_layers: 6
  gamma: 2
  num_hid: 1024
  dropout: 0.45
  activation: "swish"

# 数据加载优化 - 针对48GB GPU
data_loading:
  cache_features: true
  preload_data: true       # 48GB显存可以预加载更多数据
  use_compression: false   # 不需要压缩，显存充足
  shuffle_buffer_size: 5000  # 增加shuffle buffer

# GPU优化参数 - 针对48GB GPU
gpu_optimization:
  cudnn_benchmark: true
  cudnn_deterministic: false
  memory_fraction: 0.95    # 使用95%的显存
  allow_growth: false      # 固定显存分配

# 分布式训练优化
distributed_optimization:
  find_unused_parameters: false
  broadcast_buffers: true
  bucket_cap_mb: 50       # 增加bucket容量
  static_graph: true 